/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import controle.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import negocio.NomesAleatorios;
import negocio.Pessoa;

/**
 *
 * @author Vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {
    NomesAleatorios nomesAleatorios = new NomesAleatorios();
    Controlador controlador;
    long dataHoraAgora;
    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        try {
            controlador = new Controlador();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        controlador.selectListaPessoas();
        carregaCidades();
    }
    
    private void gerarCadastro(){
        if (txtCidade.getText().isEmpty() || txtCidade.getText().length() <= 3) {
            JOptionPane.showMessageDialog(this, "O nome da cidade não pode ser menor que 3 caracteres");
            txtCidade.requestFocus();
        } else {
            try {
                Integer.parseInt(txtCidade.getText());
                JOptionPane.showMessageDialog(this, "Não é permitido apenas números no nome da cidade");
                txtCidade.requestFocus();
            } catch (Exception e) {
                int qtde = jSliderQtde.getValue();
                
                ArrayList<String> listaNomesAleatorios = this.nomesAleatorios.getListaAleatoria(qtde);
                for (int i = 0; i < qtde; i++) {
                    dataHoraAgora = System.currentTimeMillis();
                    String nome = listaNomesAleatorios.get(i).toUpperCase();
                    String cidade = txtCidade.getText().toUpperCase();
                    //System.out.println("Cadastro " + i + ": CIDADE: " + txtCidade.getText().toUpperCase() + 
                    //        " NOME: " + listaNomesAleatorios.get(i).toUpperCase() + " DATA: " + controle.DataHora.converteParaTimestamp(dataHoraAgora));
                    controlador.cadastraPessoa(nome, cidade, controle.DataHora.converteParaTimestamp(dataHoraAgora));
                }                
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                controlador.selectListaPessoas();
                carregaCidades();
                txtCidade.setText("");
                jSliderQtde.setValue(1);
            }
        }
    }
    
    private void carregaCidades(){
        jcbCidades.removeAllItems();
        ArrayList<String> cidades = controlador.getListaCidades();
        for (int i = 0; i < cidades.size(); i++) {
            jcbCidades.addItem(cidades.get(i));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        jSliderQtde = new javax.swing.JSlider();
        lblBuscaCidade = new javax.swing.JLabel();
        jspBusca = new javax.swing.JScrollPane();
        jtaResultados = new javax.swing.JTextArea();
        jcbCidades = new javax.swing.JComboBox<>();
        lblExibeQtde = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerador de Dados");

        lblCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCidade.setText("Cidade");

        txtCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblQuantidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblQuantidade.setText("Quantidade");

        btnGerar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jSliderQtde.setMaximum(20);
        jSliderQtde.setMinimum(1);
        jSliderQtde.setValue(1);
        jSliderQtde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderQtdeStateChanged(evt);
            }
        });

        lblBuscaCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBuscaCidade.setText("Cidade");

        jtaResultados.setColumns(20);
        jtaResultados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtaResultados.setRows(5);
        jspBusca.setViewportView(jtaResultados);

        jcbCidades.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbCidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCidadesItemStateChanged(evt);
            }
        });

        lblExibeQtde.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblExibeQtde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExibeQtde.setText("1");

        btnSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidade)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGerar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jSliderQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblExibeQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscaCidade)
                        .addGap(43, 43, 43)
                        .addComponent(jcbCidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(jspBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidade)
                    .addComponent(jSliderQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExibeQtde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscaCidade)
                    .addComponent(jcbCidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderQtdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderQtdeStateChanged
        lblExibeQtde.setText(String.valueOf(jSliderQtde.getValue()));
    }//GEN-LAST:event_jSliderQtdeStateChanged

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        gerarCadastro();
    }//GEN-LAST:event_btnGerarActionPerformed

    private void jcbCidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCidadesItemStateChanged
        try {
            ArrayList<Pessoa> pessoas = controlador.getPessoasPelCidade(jcbCidades.getSelectedItem().toString());
            String resultado = "";
            for (int i = 0; i < pessoas.size(); i++) {
                resultado = resultado + pessoas.get(i).getTudo();
            }
            jtaResultados.setText(resultado);
        } catch (Exception e) {
            controlador.selectListaPessoas();
        }
    }//GEN-LAST:event_jcbCidadesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnSair;
    private javax.swing.JSlider jSliderQtde;
    private javax.swing.JComboBox<String> jcbCidades;
    private javax.swing.JScrollPane jspBusca;
    private javax.swing.JTextArea jtaResultados;
    private javax.swing.JLabel lblBuscaCidade;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblExibeQtde;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables

}
